### PR TITLE
Update sec-lmis-for-pwa.tex

### PR DESCRIPTION
**Pull request by ovaag**
According to Morten Hovd's slides equation 63 implies that a common LF can not be found

---
This change is [Reviewable](https://reviewable.io/reviews/mortenfyhn/ntnu-course-summaries/5)

### CODE REVIEW

**Comment by ovaag** [comment]
image

**Comment by mortenfyhn** [comment]
Is that equation equivalent to the one here? You're probably right, I just want to verify.

Sum(AᵀRA - R) > 0 versus Sum(AᵀR + RA) > 0

Screenshot at 2020-11-24 22-25-24

**Comment by ovaag** [comment]
Sum(AᵀRA - R) > 0 means no LF can be found for discrete systems.  
Sum(AᵀR + RA) > 0 means no LF can be found for continuous systems.
Clarified this in .tex file in new commit and updated .pdf :))

**Comment by mortenfyhn** [comment]
Claro! Thank you!

**Pull request merged**
